version: '3.9'
services:
  front-end:
    build:
      context: ./front-end  # Path to the front-end directory
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Vite dev server port for HMR
    volumes:
      - ./front-end:/app  # Mounts the front-end directory for live updates
      - /app/node_modules  # Avoids overwriting node_modules inside the container
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ensures file change detection works in Docker

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: RetroInstaRootUser
      MINIO_ROOT_PASSWORD: V7t#rP@zB9w!qQ2y$6E
    command: server /data --console-address ":9001"