services:
  front-end:
    container_name: front-end
    build:
      context: ./front-end  # Path to the front-end directory
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Vite dev server port for HMR
    volumes:
      - ./front-end:/app  # Mounts the front-end directory for live updates
      - /app/node_modules  # Avoids overwriting node_modules inside the container
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ensures file change detection works in Docker

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: RetroInstaRootUser
      MINIO_ROOT_PASSWORD: V7t#rP@zB9w!qQ2y$6E
    command: server /data --console-address ":9001"
    
  nodejs:   # Node (backend) service 
    image: server:1.0.0
    container_name: ${SERVER_HOST}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    build:
      context: ./nodejs
    env_file: .env
    volumes:
      - ./nodejs:/nodejs
      - server-v-node-modules:/server/node_modules
      - /nodejs/node_modules  # Avoids overwriting node_modules inside the container
    depends_on:
      - mongo

  mongo:    # Database service
    container_name: mongo
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    build:
      context: ./mongo
    env_file: .env
    volumes:
      - database-v:/data/db

volumes:
  server-v-node-modules:
    name: "server-v-node-modules"
  database-v:
    name: "database-v"
