version: '3.9'
services:
  front-end:
    build:
      context: ./front-end  # Path to the front-end directory
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Vite dev server port for HMR
    volumes:
      - ./front-end:/app  # Mounts the front-end directory for live updates
      - /app/node_modules  # Avoids overwriting node_modules inside the container
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ensures file change detection works in Docker
